FROM __BASEIMAGE_ARCH__/alpine
MAINTAINER Jonathan Weisberg <jo.weisberg@gmail.com>

__CROSS_COPY qemu-__QEMU_ARCH__-static /usr/bin
RUN apk --no-cache --update add bash openssl jq

WORKDIR /root
VOLUME /mnt/data

COPY certs-extraction.sh /root/certs-extraction.sh
COPY healthcheck /usr/bin/healthcheck
RUN chmod +x /usr/bin/healthcheck

CMD ["/bin/bash", "/root/certs-extraction.sh"]